#!/bin/bash
set -e

# Moodle auto-configuration entrypoint
# Persists config.php inside the moodledata volume so it survives
# container recreations and server reboots without bind-mount issues.

CONFIG_FILE="/var/www/html/config.php"
CONFIG_BACKUP="/var/www/moodledata/.config.php"
MOODLEDATA_DIR="/var/www/moodledata"

# Fix permissions on moodledata (mounted volume)
if [ -d "$MOODLEDATA_DIR" ]; then
    chown -R www-data:www-data "$MOODLEDATA_DIR"
    chmod -R 777 "$MOODLEDATA_DIR"
fi

# Restore config.php from moodledata backup if it exists
if [ -f "$CONFIG_BACKUP" ]; then
    echo ">>> Restoring config.php from moodledata backup..."
    cp "$CONFIG_BACKUP" "$CONFIG_FILE"
    chown www-data:www-data "$CONFIG_FILE"
    chmod 644 "$CONFIG_FILE"

    # Ensure wwwroot is updated if MOODLE_URL changed
    if [ -n "$MOODLE_URL" ]; then
        CURRENT_URL=$(php -r "include '$CONFIG_FILE'; echo \$CFG->wwwroot;" 2>/dev/null || echo "")
        if [ "$CURRENT_URL" != "$MOODLE_URL" ] && [ -n "$CURRENT_URL" ]; then
            echo ">>> Updating wwwroot from '$CURRENT_URL' to '$MOODLE_URL'..."
            sed -i "s|\$CFG->wwwroot\s*=.*|\$CFG->wwwroot   = '$MOODLE_URL';|" "$CONFIG_FILE"
            # Sync the update back to the backup
            cp "$CONFIG_FILE" "$CONFIG_BACKUP"
        fi
    fi

    echo ">>> config.php restored successfully."

# Generate fresh config.php from environment variables
else
    echo ">>> Moodle config.php not found. Generating from environment variables..."

    cat > "$CONFIG_FILE" << 'MOODLECONFIG'
<?php
// Moodle configuration file auto-generated by moocker entrypoint

unset($CFG);
global $CFG;
$CFG = new stdClass();

$CFG->dbtype    = getenv('MOODLE_DATABASE_TYPE') ?: 'mariadb';
$CFG->dblibrary = 'native';
$CFG->dbhost    = getenv('MOODLE_DATABASE_HOST') ?: 'db';
$CFG->dbname    = getenv('MOODLE_DATABASE_NAME') ?: 'moodle';
$CFG->dbuser    = getenv('MOODLE_DATABASE_USER') ?: 'moodleuser';
$CFG->dbpass    = getenv('MOODLE_DATABASE_PASSWORD') ?: 'moodlepass';
$CFG->prefix    = 'mdl_';
$CFG->dboptions = array(
    'dbpersist' => false,
    'dbport'    => '',
    'dbsocket'  => '',
    'dbcollation' => 'utf8mb4_unicode_ci',
);

$CFG->wwwroot   = getenv('MOODLE_URL') ?: 'http://localhost:8080';
$CFG->dataroot  = '/var/www/moodledata';
$CFG->admin     = 'admin';

$CFG->directorypermissions = 0777;

$CFG->sslproxy  = false;

require_once(__DIR__ . '/lib/setup.php');
MOODLECONFIG

    # Set proper ownership
    chown www-data:www-data "$CONFIG_FILE"
    chmod 644 "$CONFIG_FILE"

    # Save backup to persistent moodledata volume
    cp "$CONFIG_FILE" "$CONFIG_BACKUP"

    echo ">>> config.php generated and backed up successfully."
fi

# Hand off to Apache
exec apache2-foreground
