#!/bin/bash
set -e

# Moodle auto-configuration entrypoint
# Generates config.php from environment variables on every container start,
# so changes to .env (DB host, name, user, password, URL) take effect immediately.

CONFIG_FILE="/var/www/html/config.php"
MOODLEDATA_DIR="/var/www/moodledata"

# Fix permissions on moodledata (mounted volume)
if [ -d "$MOODLEDATA_DIR" ]; then
    chown -R www-data:www-data "$MOODLEDATA_DIR"
    chmod -R 777 "$MOODLEDATA_DIR"
fi

# Resolve env vars at bash level — NOT via PHP getenv() which fails without variables_order=E
DB_TYPE="${MOODLE_DATABASE_TYPE:-mariadb}"
DB_HOST="${MOODLE_DATABASE_HOST:-db}"
DB_NAME="${MOODLE_DATABASE_NAME:-moodle}"
DB_USER="${MOODLE_DATABASE_USER:-moodleuser}"
DB_PASS="${MOODLE_DATABASE_PASSWORD:-moodlepass}"
WWWROOT="${MOODLE_URL:-http://localhost:8080}"

echo ">>> Generating config.php from environment variables..."

cat > "$CONFIG_FILE" << MOODLECONFIG
<?php
// Moodle configuration file auto-generated by moocker entrypoint

unset(\$CFG);
global \$CFG;
\$CFG = new stdClass();

\$CFG->dbtype    = '${DB_TYPE}';
\$CFG->dblibrary = 'native';
\$CFG->dbhost    = '${DB_HOST}';
\$CFG->dbname    = '${DB_NAME}';
\$CFG->dbuser    = '${DB_USER}';
\$CFG->dbpass    = '${DB_PASS}';
\$CFG->prefix    = 'mdl_';
\$CFG->dboptions = array(
    'dbpersist' => false,
    'dbport'    => '',
    'dbsocket'  => '',
    'dbcollation' => 'utf8mb4_unicode_ci',
);

\$CFG->wwwroot   = '${WWWROOT}';
\$CFG->dataroot  = '/var/www/moodledata';
\$CFG->admin     = 'admin';

\$CFG->directorypermissions = 0777;

require_once(__DIR__ . '/lib/setup.php');
MOODLECONFIG

chown www-data:www-data "$CONFIG_FILE"
chmod 644 "$CONFIG_FILE"

echo ">>> config.php generated successfully."

# Hand off to Apache
exec apache2-foreground
