#!/bin/bash
set -e

# Moodle auto-configuration entrypoint
# Generates config.php from environment variables on every container start,
# runs pending database upgrades via CLI, then starts Apache.

CONFIG_FILE="/var/www/html/config.php"
MOODLEDATA_DIR="/var/www/moodledata"

# Fix permissions on moodledata (mounted volume)
if [ -d "$MOODLEDATA_DIR" ]; then
    chown -R www-data:www-data "$MOODLEDATA_DIR"
    chmod -R 777 "$MOODLEDATA_DIR"

    # Purge stale caches that cause issues after PHP/Moodle version upgrades
    echo ">>> Purging Moodle caches..."
    rm -rf "$MOODLEDATA_DIR/cache" "$MOODLEDATA_DIR/localcache" "$MOODLEDATA_DIR/muc" 2>/dev/null || true
fi

# Resolve env vars at bash level
DB_TYPE="${MOODLE_DATABASE_TYPE:-mariadb}"
DB_HOST="${MOODLE_DATABASE_HOST:-db}"
DB_NAME="${MOODLE_DATABASE_NAME:-moodle}"
DB_USER="${MOODLE_DATABASE_USER:-moodleuser}"
DB_PASS="${MOODLE_DATABASE_PASSWORD:-moodlepass}"
WWWROOT="${MOODLE_URL:-http://localhost:8080}"

# Auto-detect sslproxy: if wwwroot uses https://, enable it automatically
# Can be overridden by explicitly setting MOODLE_SSLPROXY env var
if [ -n "${MOODLE_SSLPROXY+x}" ]; then
    SSLPROXY="${MOODLE_SSLPROXY}"
elif [[ "$WWWROOT" == https://* ]]; then
    SSLPROXY="true"
else
    SSLPROXY="false"
fi

echo ">>> Generating config.php..."
echo "    wwwroot:  ${WWWROOT}"
echo "    dbhost:   ${DB_HOST}"
echo "    dbname:   ${DB_NAME}"
echo "    dbuser:   ${DB_USER}"
echo "    sslproxy: ${SSLPROXY}"

cat > "$CONFIG_FILE" << MOODLECONFIG
<?php
// Moodle configuration file auto-generated by moocker entrypoint

unset(\$CFG);
global \$CFG;
\$CFG = new stdClass();

\$CFG->dbtype    = '${DB_TYPE}';
\$CFG->dblibrary = 'native';
\$CFG->dbhost    = '${DB_HOST}';
\$CFG->dbname    = '${DB_NAME}';
\$CFG->dbuser    = '${DB_USER}';
\$CFG->dbpass    = '${DB_PASS}';
\$CFG->prefix    = 'mdl_';
\$CFG->dboptions = array(
    'dbpersist' => 0,
    'dbport'    => '',
    'dbsocket'  => '',
    'dbcollation' => 'utf8mb4_unicode_ci',
);

\$CFG->wwwroot   = '${WWWROOT}';
\$CFG->dataroot  = '/var/www/moodledata';
\$CFG->dirroot   = '/var/www/html';
\$CFG->libdir    = '/var/www/html/lib';
\$CFG->admin     = 'admin';

\$CFG->directorypermissions = 0777;

\$CFG->sslproxy  = ${SSLPROXY};

// When behind a reverse proxy that terminates SSL, force HTTPS detection
// before setup.php runs its wwwroot check (otherwise http vs https mismatch = redirect loop)
if (!empty(\$CFG->sslproxy)) {
    \$_SERVER['HTTPS'] = 'on';
}

require_once(__DIR__ . '/lib/setup.php');
MOODLECONFIG

chown www-data:www-data "$CONFIG_FILE"
chmod 644 "$CONFIG_FILE"

echo ">>> config.php written."

# Run any pending database upgrades via CLI (avoids web redirect loops)
echo ">>> Checking for pending Moodle upgrades..."
if php /var/www/html/admin/cli/upgrade.php --non-interactive --allow-unstable 2>&1; then
    echo ">>> Upgrade check complete."
else
    echo ">>> Upgrade check finished with warnings (this is normal for first run)."
fi

# Hand off to Apache
exec apache2-foreground
